# Generated by Django 5.2.9 on 2025-12-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='job_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('application_url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('bookmarked', 'BOOKMARKED'), ('applying', 'APPLYING'), ('applied', 'APPLIED'), ('interviewing', 'INTERVIEWING'), ('offer', 'OFFER'), ('rejected', 'REJECTED')], default='bookmarked', max_length=12)),
                ('date_applied', models.DateField()),
                ('salary_range', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_tracker.user')),
            ],
        ),
    ]
