# Generated by Django 5.2.9 on 2025-12-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_applications',
            new_name='Job_Application',
        ),
    ]
