# Generated by Django 5.2.9 on 2025-12-17 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0003_alter_user_email_alter_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('application_url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('bookmarked', 'BOOKMARKED'), ('applying', 'APPLYING'), ('applied', 'APPLIED'), ('interviewing', 'INTERVIEWING'), ('offer', 'OFFER'), ('rejected', 'REJECTED')], default='bookmarked', max_length=12)),
                ('date_applied', models.DateField()),
                ('salary_range', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_tracker.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Job_Application',
        ),
    ]
