# Generated by Django 5.2.9 on 2025-12-17 22:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0005_alter_jobapplication_user_id_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(verbose_name=100)),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_url',
            field=models.URLField(max_length=500),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name=50)),
                ('last_name', models.CharField(verbose_name=50)),
                ('email', models.EmailField(max_length=254, verbose_name=100)),
                ('linkedin', models.URLField(verbose_name=100)),
                ('phone_company', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_tracker.company')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'RESUME'), ('cover_letter', 'COVER_LETTER'), ('other', 'OTHER')], default='resume', max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('job_application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_tracker.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField()),
                ('follow_up_type', models.CharField(choices=[('post_application', 'POST_APPLICATION'), ('post_interview', 'POST_INTERVIEW'), ('thnak_you', 'THANK_YOU'), ('check_in', 'CHECK_IN'), ('networking', 'NETWORKING')], max_length=16)),
                ('follow_up_method', models.CharField(choices=[('email', 'EMAIL'), ('phone', 'PHONE'), ('linkedin', 'LINKEDIN'), ('in_person', 'IN_PERSON')], max_length=9)),
                ('subject_line', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('notes', models.TextField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_tracker.contactperson')),
                ('job_application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_tracker.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_format', models.CharField(choices=[('phone', 'PHONE'), ('video', 'VIDEO'), ('onsite', 'ONSITE')], max_length=6)),
                ('interview_type', models.CharField(choices=[('phone_screen', 'PHONE_SCREEN'), ('one_on_one', 'ONE_ON_ONE'), ('group', 'GROUP')], max_length=12)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('interviewer_name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_tracker.jobapplication')),
            ],
        ),
    ]
